import random
import time
import allure
import pytest
from base.base_test import BaseTest
from faker import Faker

@allure.feature("Registration Contractor")
class TestRegistrationContractor(BaseTest):

    def test_registration_contractor(self):
        self.welcome_page.open()
        self.welcome_page.click_get_started()
        self.registration_type_page.is_opened()
        self.registration_type_page.select_contractor_type()
        self.registration_type_page.click_checkbox()
        self.registration_type_page.click_register()
        self.registration_contractor_page.is_opened()
        self.registration_contractor_page.enter_first_name(f"Test{random.randint(1, 100)}")
        self.registration_contractor_page.enter_last_name(f"Auto{random.randint(1, 100)}")
        self.registration_contractor_page.click_main_specialization()
        self.registration_contractor_page.select_specialization()
        self.registration_contractor_page.enter_years_experience("5")
        self.registration_contractor_page.click_country()
        self.registration_contractor_page.select_country()
        self.registration_contractor_page.enter_city("a")
        self.registration_contractor_page.select_city()
        self.registration_contractor_page.click_next_step()
        self.registration_contractor_page.enter_password(self.data.PASSWORD)
        self.registration_contractor_page.enter_repeat_password(self.data.PASSWORD)
        self.registration_contractor_page.enter_email()
        self.registration_contractor_page.enter_phone_number(self.data.PHONE_NUMBER)
        self.registration_contractor_page.click_next_step2()
        self.registration_contractor_page.enter_cover_letter(self.data.COVER_LETTER)
        self.registration_contractor_page.click_add_specialization()
        self.registration_contractor_page.click_main_specialization_2()
        self.registration_contractor_page.select_specialization_2()
        self.registration_contractor_page.enter_years_experience_2("4")
        self.registration_contractor_page.click_skills_1()
        self.registration_contractor_page.select_skills_1()
        self.registration_contractor_page.enter_skills_years_exper_1("5")
        self.registration_contractor_page.click_skills_2()
        self.registration_contractor_page.select_skills_2()
        self.registration_contractor_page.enter_skills_years_exper_2("4")
        self.registration_contractor_page.click_skills_3()
        self.registration_contractor_page.select_skills_3()
        self.registration_contractor_page.enter_skills_years_exper_3("3")
        self.registration_contractor_page.click_language()
        self.registration_contractor_page.select_language()
        self.registration_contractor_page.click_level()
        self.registration_contractor_page.select_level()
        self.registration_contractor_page.enter_soc_media_links1(self.data.SOC_MEDIA_LINKS)
        self.registration_contractor_page.enter_soc_media_links2(self.data.SOC_MEDIA_LINKS)
        self.registration_contractor_page.enter_soc_media_links3(self.data.SOC_MEDIA_LINKS)
        self.registration_contractor_page.enter_soc_media_links4(self.data.SOC_MEDIA_LINKS)
        self.registration_contractor_page.enter_soc_media_links5(self.data.SOC_MEDIA_LINKS)
        self.registration_contractor_page.click_checkbox()
        self.registration_contractor_page.click_finish()
        self.home_page.is_opened()

        time.sleep(5)
