

class RegistrationContractorLocators:

    FIRST_NAME_ENTER = ("xpath", "//input[@id='introduce-contractor_name']")
    LAST_NAME_ENTER = ("xpath", "//input[@id='introduce-contractor_surname']")
    MAIN_SPECIALIZATION_1 = ("xpath", "(//span[@class='ant-select-selection-search'])[1]")
    SELECT_SPECIALIZATION_1 = ("xpath", "//div[@title='Frontend Development']")
    SPECIALIZATION_YEARS_EXPERIENCE = ("xpath", "//input[@id='introduce-contractor_specializations_0_specialization_experience']")
    COUNTRY = ("xpath", "(//span[@class='ant-select-selection-search'])[2]")
    SELECT_COUNTRY = ("xpath", "//div[@title='Albania']")
    CITY = ("xpath", "//input[@id='introduce-contractor_city']")
    SELECT_CITY = ("xpath", "//div[@title='Elbasan']")
    NEXT_STEP_BUTTON = ("xpath", "//button[text()='Next step']")
    PASSWORD_ENTER = ("xpath", "//input[@id='security_password']")
    REPEAT_PASSWORD_ENTER = ("xpath", "//input[@id='security_password_confirmation']")
    EMAIL = ("xpath", "//input[@type='email']")
    PHONE_NUMBER = ("xpath", "//input[@type='tel']")
    NEXT_STEP_BUTTON2 = ("xpath", "(//button[@type='submit'])[2]")
    COVER_LETTER = ("xpath", "//textarea[@placeholder='Cover letter']")
    ADD_SPECIALIZATION = ("xpath", "//span[text()='Add specialization']")
    MAIN_SPECIALIZATION_2 = ("xpath", "(//span[@class='ant-select-selection-search'])[5]")
    SELECT_SPECIALIZATION_2 = ("xpath", "(//div[@title='Graphic Designer'])[2]")
    SPECIALIZATION_YEARS_EXPERIENCE_2 = ("xpath", "//input[@id='personalization_specializations_1_specialization_experience']")
    SKILLS_1 = ("xpath", "(//div[@class='ant-select-selector'])[6]")
    SELECT_SKILLS_1 = ("xpath", "//div[@title='Java']")
    SKILLS_YEARS_EXPERIENCE_1 = ("xpath", "//input[@id='personalization_skills_0_skill_experience']")
    SKILLS_2 = ("xpath", "(//div[@class='ant-select-selector'])[7]")
    SELECT_SKILLS_2 = ("xpath", "(//div[@title='Javascript'])[2]")
    SKILLS_YEARS_EXPERIENCE_2 = ("xpath", "//input[@id='personalization_skills_1_skill_experience']")
    SKILLS_3 = ("xpath", "(//div[@class='ant-select-selector'])[8]")
    SELECT_SKILLS_3 = ("xpath", "(//div[@title='Python'])[3]")
    SKILLS_YEARS_EXPERIENCE_3 = ("xpath", "//input[@id='personalization_skills_2_skill_experience']")
    LANGUAGE = ("xpath", "(//div[@class='ant-select-selector'])[9]")
    SELECT_LANGUAGE = ("xpath", "//div[@title='Afrikaans']")
    LEVEL = ("xpath", "(//div[@class='ant-select-selector'])[10]")
    SELECT_LEVEL = ("xpath", "//div[@title='B2']")
    SOCIAL_MEDIA_LINKS1 = ("xpath", "//input[@ placeholder ='https:/www.behance.com/']")
    SOCIAL_MEDIA_LINKS2 = ("xpath", "//input[@ placeholder ='https://www.linkedin.com']")
    SOCIAL_MEDIA_LINKS3 = ("xpath", "//input[@ placeholder ='https:/www.dribbble.com/']")
    SOCIAL_MEDIA_LINKS4 = ("xpath", "//input[@ placeholder ='https:/www.facebook.com/']")
    SOCIAL_MEDIA_LINKS5 = ("xpath", "//input[@ placeholder ='https:/www.xing.com/']")
    CHECKBOX_REGISTR_FINISH = ("xpath", "//input[@type='checkbox']")
    FINISH_BUTTON = ("xpath", "//button[text()='Finish']")